=== maxim-zaytsev/arkanoid/src/main/flex/levels/level.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="level" type="levelType"/>
  <xs:complexType name="rowType">
    <xs:sequence>
      <xs:element name="cell" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="xs:string" name="block" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="levelType">
    <xs:sequence>
      <xs:element type="blocksType" name="blocks">
        <xs:annotation>
          <xs:documentation>field height = 600field width = 500bat height = 15 ball height = 10. 2 rows are occupied by them,
    so we have 38 rows
    and 10 columnsblock size = 100 x 15</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:string" name="bat"/>
      <xs:element type="xs:string" name="ball"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cellType">
    <xs:sequence>
      <xs:element type="xs:string" name="block" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="blocksType">
    <xs:sequence>
      <xs:element type="rowType" name="row" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== maxim-zaytsev/arkanoid/src/main/flex/levels/level2.xml
<?xml version="1.0" encoding="utf-8"
        xmlns="http://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com level.xsd"
        ?>
<level>
    <!--field height = 600-->
    <!--field width = 500-->
    <!--bat height = 15 ball height = 10. 2 rows are occupied by them,
    so we have 38 rows
    and 10 columns-->
    <!--block size = 100 x 15-->
    <blocks>
        <row>
            <cell><block type="" bonus=""/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
        <row>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
            <cell><block/></cell>
        </row>
    </blocks>
    <bat></bat>
    <ball></ball>
</level>
